version: '2.2' # Adjust if needed

services:
  db:
    image: my-postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data # Named volume
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=myprojectdb
  web:
    image: my-django-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app # Mount your Django project for development

volumes:
  postgres_data: 
